import type {
  ActivityFeedItem,
  CalendarEvent,
  Customer,
  Deal,
  Lead,
  Message,
  Notification,
  Task,
  TeamMember,
} from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "l1",
    name: "Sarah Mitchell",
    company: "TechNova Inc.",
    email: "sarah@technova.io",
    phone: "+1 (555) 201-4400",
    source: "Website",
    status: "Qualified",
    assignedTo: "Alex Rivera",
    dealValue: 42000,
    priority: "High",
    lastContact: "2026-04-18",
    nextFollowUp: "2026-04-25",
    tags: ["enterprise", "SaaS"],
    notes: "Interested in annual plan",
  },
  {
    id: "l2",
    name: "James Thornton",
    company: "Meridian Group",
    email: "j.thornton@meridian.com",
    phone: "+1 (555) 309-7722",
    source: "LinkedIn",
    status: "Proposal",
    assignedTo: "Maria Chen",
    dealValue: 78500,
    priority: "Urgent",
    lastContact: "2026-04-20",
    nextFollowUp: "2026-04-22",
    tags: ["finance", "mid-market"],
    notes: "Needs custom integration",
  },
  {
    id: "l3",
    name: "Priya Kapoor",
    company: "BrightPath Analytics",
    email: "priya@brightpath.ai",
    phone: "+1 (555) 447-0011",
    source: "Referral",
    status: "New",
    assignedTo: "David Park",
    dealValue: 15000,
    priority: "Medium",
    lastContact: "2026-04-15",
    nextFollowUp: "2026-04-28",
    tags: ["analytics", "startup"],
    notes: "Budget approval pending",
  },
  {
    id: "l4",
    name: "Marcus Johnson",
    company: "Summit Real Estate",
    email: "marcus@summitrealty.com",
    phone: "+1 (555) 512-3344",
    source: "Cold Email",
    status: "Contacted",
    assignedTo: "Alex Rivera",
    dealValue: 22000,
    priority: "Low",
    lastContact: "2026-04-10",
    nextFollowUp: "2026-04-30",
    tags: ["real estate"],
    notes: "Follow up after conference",
  },
  {
    id: "l5",
    name: "Elena Vasquez",
    company: "ClearStream Media",
    email: "elena@clearstream.tv",
    phone: "+1 (555) 678-9900",
    source: "Trade Show",
    status: "Negotiation",
    assignedTo: "Maria Chen",
    dealValue: 95000,
    priority: "Urgent",
    lastContact: "2026-04-21",
    nextFollowUp: "2026-04-23",
    tags: ["media", "enterprise"],
    notes: "Final pricing discussion",
  },
  {
    id: "l6",
    name: "Robert Kim",
    company: "Apex Logistics",
    email: "r.kim@apexlog.net",
    phone: "+1 (555) 723-4561",
    source: "Partner",
    status: "Won",
    assignedTo: "David Park",
    dealValue: 56000,
    priority: "High",
    lastContact: "2026-04-19",
    nextFollowUp: "2026-05-05",
    tags: ["logistics", "partner"],
    notes: "Signed — onboarding next week",
  },
  {
    id: "l7",
    name: "Amanda Brooks",
    company: "FutureLabs Corp",
    email: "amanda@futurelabs.io",
    phone: "+1 (555) 834-2200",
    source: "Website",
    status: "Lost",
    assignedTo: "Sophia Lee",
    dealValue: 33000,
    priority: "Medium",
    lastContact: "2026-04-05",
    nextFollowUp: "",
    tags: ["R&D"],
    notes: "Went with competitor",
  },
  {
    id: "l8",
    name: "Daniel Carter",
    company: "Pinpoint Marketing",
    email: "daniel@pinpoint.co",
    phone: "+1 (555) 912-6655",
    source: "LinkedIn",
    status: "Qualified",
    assignedTo: "Alex Rivera",
    dealValue: 18500,
    priority: "High",
    lastContact: "2026-04-17",
    nextFollowUp: "2026-04-26",
    tags: ["marketing", "SMB"],
    notes: "Demo scheduled",
  },
  {
    id: "l9",
    name: "Nina Johansson",
    company: "Nordic Capital",
    email: "nina@nordiccap.se",
    phone: "+46 70 123 4567",
    source: "Referral",
    status: "Proposal",
    assignedTo: "Maria Chen",
    dealValue: 120000,
    priority: "Urgent",
    lastContact: "2026-04-20",
    nextFollowUp: "2026-04-24",
    tags: ["finance", "enterprise", "europe"],
    notes: "High-value opportunity",
  },
  {
    id: "l10",
    name: "Tyler Watson",
    company: "Catalyst Ventures",
    email: "tyler@catalystvc.com",
    phone: "+1 (555) 044-8833",
    source: "Event",
    status: "New",
    assignedTo: "David Park",
    dealValue: 8000,
    priority: "Low",
    lastContact: "2026-04-14",
    nextFollowUp: "2026-05-01",
    tags: ["VC", "startup"],
    notes: "Early-stage inquiry",
  },
  {
    id: "l11",
    name: "Fatima Al-Rashid",
    company: "Gulf Tech Solutions",
    email: "fatima@gulftech.ae",
    phone: "+971 50 789 1234",
    source: "Website",
    status: "Contacted",
    assignedTo: "Sophia Lee",
    dealValue: 65000,
    priority: "High",
    lastContact: "2026-04-16",
    nextFollowUp: "2026-04-27",
    tags: ["enterprise", "MEA"],
    notes: "Regional expansion interest",
  },
  {
    id: "l12",
    name: "Chris Yamamoto",
    company: "Pacific Trade Co.",
    email: "c.yamamoto@pactrade.jp",
    phone: "+81 3 5555 7890",
    source: "Partner",
    status: "Qualified",
    assignedTo: "Alex Rivera",
    dealValue: 44000,
    priority: "Medium",
    lastContact: "2026-04-18",
    nextFollowUp: "2026-04-29",
    tags: ["trade", "APAC"],
    notes: "Partnership evaluation",
  },
  {
    id: "l13",
    name: "Grace Obi",
    company: "AfriTech Innovations",
    email: "grace@afritech.ng",
    phone: "+234 80 1234 5678",
    source: "Cold Email",
    status: "New",
    assignedTo: "Maria Chen",
    dealValue: 12500,
    priority: "Low",
    lastContact: "2026-04-12",
    nextFollowUp: "2026-05-03",
    tags: ["startup", "Africa"],
    notes: "Series A funded",
  },
  {
    id: "l14",
    name: "Benjamin Stark",
    company: "Harbor Insurance",
    email: "b.stark@harborins.com",
    phone: "+1 (555) 156-7890",
    source: "LinkedIn",
    status: "Negotiation",
    assignedTo: "David Park",
    dealValue: 89000,
    priority: "High",
    lastContact: "2026-04-21",
    nextFollowUp: "2026-04-23",
    tags: ["insurance", "enterprise"],
    notes: "Legal review in progress",
  },
  {
    id: "l15",
    name: "Isabella Romano",
    company: "Milan Fashion House",
    email: "isabella@milanfashion.it",
    phone: "+39 02 1234 5678",
    source: "Trade Show",
    status: "Contacted",
    assignedTo: "Sophia Lee",
    dealValue: 27500,
    priority: "Medium",
    lastContact: "2026-04-13",
    nextFollowUp: "2026-04-28",
    tags: ["fashion", "luxury"],
    notes: "Seasonal campaign interest",
  },
  {
    id: "l16",
    name: "Noah Williams",
    company: "GreenEnergy Corp",
    email: "noah@greenenergy.io",
    phone: "+1 (555) 267-4422",
    source: "Website",
    status: "Qualified",
    assignedTo: "Alex Rivera",
    dealValue: 53000,
    priority: "High",
    lastContact: "2026-04-19",
    nextFollowUp: "2026-04-25",
    tags: ["energy", "sustainability"],
    notes: "ESG reporting requirements",
  },
  {
    id: "l17",
    name: "Olivia Chang",
    company: "HealthFirst Medical",
    email: "olivia@healthfirst.com",
    phone: "+1 (555) 378-5533",
    source: "Referral",
    status: "Proposal",
    assignedTo: "Maria Chen",
    dealValue: 74000,
    priority: "High",
    lastContact: "2026-04-20",
    nextFollowUp: "2026-04-24",
    tags: ["healthcare", "mid-market"],
    notes: "HIPAA compliance needed",
  },
  {
    id: "l18",
    name: "Lucas Fernandez",
    company: "Samba Digital",
    email: "lucas@sambadigital.br",
    phone: "+55 11 9876 5432",
    source: "Partner",
    status: "New",
    assignedTo: "David Park",
    dealValue: 9500,
    priority: "Low",
    lastContact: "2026-04-11",
    nextFollowUp: "2026-05-02",
    tags: ["digital", "LatAm"],
    notes: "Partnership inquiry",
  },
  {
    id: "l19",
    name: "Sophie Martin",
    company: "Paris Consulting",
    email: "sophie@parisconsult.fr",
    phone: "+33 1 2345 6789",
    source: "Event",
    status: "Contacted",
    assignedTo: "Sophia Lee",
    dealValue: 31000,
    priority: "Medium",
    lastContact: "2026-04-15",
    nextFollowUp: "2026-04-29",
    tags: ["consulting", "Europe"],
    notes: "RFP submitted",
  },
  {
    id: "l20",
    name: "Ethan Harper",
    company: "Vertex Software",
    email: "ethan@vertexsw.com",
    phone: "+1 (555) 489-6644",
    source: "Website",
    status: "Won",
    assignedTo: "Alex Rivera",
    dealValue: 61000,
    priority: "High",
    lastContact: "2026-04-22",
    nextFollowUp: "2026-05-10",
    tags: ["software", "SaaS"],
    notes: "Deal closed — kickoff call booked",
  },
];

export const mockDeals: Deal[] = [
  {
    id: "d1",
    title: "TechNova Enterprise Suite",
    company: "TechNova Inc.",
    companyLogo: "TN",
    contact: "Sarah Mitchell",
    value: 42000,
    probability: 75,
    expectedCloseDate: "2026-05-15",
    stage: "Negotiation",
    owner: "Alex Rivera",
    notes: "Final pricing being discussed",
    tasks: [
      { id: "t1", title: "Send revised proposal", completed: true },
      { id: "t2", title: "Schedule demo call", completed: false },
    ],
    attachments: ["proposal-v2.pdf"],
  },
  {
    id: "d2",
    title: "Meridian Integration Project",
    company: "Meridian Group",
    companyLogo: "MG",
    contact: "James Thornton",
    value: 78500,
    probability: 85,
    expectedCloseDate: "2026-05-01",
    stage: "Contract",
    owner: "Maria Chen",
    notes: "Awaiting legal sign-off",
    tasks: [
      { id: "t3", title: "Legal review", completed: false },
      { id: "t4", title: "Prepare onboarding docs", completed: false },
    ],
    attachments: ["contract-draft.pdf", "SLA.pdf"],
  },
  {
    id: "d3",
    title: "BrightPath Analytics License",
    company: "BrightPath Analytics",
    companyLogo: "BA",
    contact: "Priya Kapoor",
    value: 15000,
    probability: 40,
    expectedCloseDate: "2026-06-01",
    stage: "Proposal",
    owner: "David Park",
    notes: "Budget approval Q2",
    tasks: [{ id: "t5", title: "Follow up budget approval", completed: false }],
    attachments: [],
  },
  {
    id: "d4",
    title: "Nordic Capital Platform",
    company: "Nordic Capital",
    companyLogo: "NC",
    contact: "Nina Johansson",
    value: 120000,
    probability: 90,
    expectedCloseDate: "2026-04-30",
    stage: "Contract",
    owner: "Maria Chen",
    notes: "High priority deal",
    tasks: [
      { id: "t6", title: "Final review call", completed: true },
      { id: "t7", title: "Countersign agreement", completed: false },
    ],
    attachments: ["nordic-contract.pdf"],
  },
  {
    id: "d5",
    title: "Summit CRM Rollout",
    company: "Summit Real Estate",
    companyLogo: "SR",
    contact: "Marcus Johnson",
    value: 22000,
    probability: 30,
    expectedCloseDate: "2026-06-15",
    stage: "Qualified",
    owner: "Alex Rivera",
    notes: "Initial qualification complete",
    tasks: [],
    attachments: [],
  },
  {
    id: "d6",
    title: "ClearStream Media Hub",
    company: "ClearStream Media",
    companyLogo: "CS",
    contact: "Elena Vasquez",
    value: 95000,
    probability: 80,
    expectedCloseDate: "2026-05-10",
    stage: "Negotiation",
    owner: "Maria Chen",
    notes: "Negotiating usage tiers",
    tasks: [{ id: "t8", title: "Prepare pricing matrix", completed: true }],
    attachments: ["pricing-matrix.xlsx"],
  },
  {
    id: "d7",
    title: "Apex Logistics Suite",
    company: "Apex Logistics",
    companyLogo: "AL",
    contact: "Robert Kim",
    value: 56000,
    probability: 100,
    expectedCloseDate: "2026-04-19",
    stage: "Won",
    owner: "David Park",
    notes: "Closed and onboarding",
    tasks: [{ id: "t9", title: "Send welcome kit", completed: true }],
    attachments: [],
  },
  {
    id: "d8",
    title: "Harbor Insurance Platform",
    company: "Harbor Insurance",
    companyLogo: "HI",
    contact: "Benjamin Stark",
    value: 89000,
    probability: 70,
    expectedCloseDate: "2026-05-20",
    stage: "Proposal",
    owner: "David Park",
    notes: "Insurance-specific requirements",
    tasks: [{ id: "t10", title: "Security assessment", completed: false }],
    attachments: [],
  },
  {
    id: "d9",
    title: "HealthFirst HIPAA Module",
    company: "HealthFirst Medical",
    companyLogo: "HF",
    contact: "Olivia Chang",
    value: 74000,
    probability: 65,
    expectedCloseDate: "2026-05-25",
    stage: "Proposal",
    owner: "Maria Chen",
    notes: "Compliance check needed",
    tasks: [],
    attachments: [],
  },
  {
    id: "d10",
    title: "Vertex Software Growth",
    company: "Vertex Software",
    companyLogo: "VS",
    contact: "Ethan Harper",
    value: 61000,
    probability: 100,
    expectedCloseDate: "2026-04-22",
    stage: "Won",
    owner: "Alex Rivera",
    notes: "Kickoff call scheduled",
    tasks: [{ id: "t11", title: "Kickoff meeting prep", completed: true }],
    attachments: [],
  },
  {
    id: "d11",
    title: "GreenEnergy ESG Toolkit",
    company: "GreenEnergy Corp",
    companyLogo: "GE",
    contact: "Noah Williams",
    value: 53000,
    probability: 55,
    expectedCloseDate: "2026-05-30",
    stage: "Qualified",
    owner: "Alex Rivera",
    notes: "ESG features requested",
    tasks: [],
    attachments: [],
  },
  {
    id: "d12",
    title: "FutureLabs Platform",
    company: "FutureLabs Corp",
    companyLogo: "FL",
    contact: "Amanda Brooks",
    value: 33000,
    probability: 0,
    expectedCloseDate: "2026-04-15",
    stage: "Lost",
    owner: "Sophia Lee",
    notes: "Competitor selected",
    tasks: [],
    attachments: [],
  },
  {
    id: "d13",
    title: "Pinpoint Analytics Pro",
    company: "Pinpoint Marketing",
    companyLogo: "PM",
    contact: "Daniel Carter",
    value: 18500,
    probability: 60,
    expectedCloseDate: "2026-05-20",
    stage: "Qualified",
    owner: "Alex Rivera",
    notes: "Demo completed",
    tasks: [],
    attachments: [],
  },
  {
    id: "d14",
    title: "Gulf Tech Enterprise",
    company: "Gulf Tech Solutions",
    companyLogo: "GT",
    contact: "Fatima Al-Rashid",
    value: 65000,
    probability: 50,
    expectedCloseDate: "2026-06-10",
    stage: "Prospect",
    owner: "Sophia Lee",
    notes: "Regional proposal pending",
    tasks: [],
    attachments: [],
  },
  {
    id: "d15",
    title: "Paris Consulting Suite",
    company: "Paris Consulting",
    companyLogo: "PC",
    contact: "Sophie Martin",
    value: 31000,
    probability: 45,
    expectedCloseDate: "2026-06-01",
    stage: "Prospect",
    owner: "Sophia Lee",
    notes: "RFP evaluation ongoing",
    tasks: [],
    attachments: [],
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "Robert Kim",
    email: "r.kim@apexlog.net",
    phone: "+1 (555) 723-4561",
    company: "Apex Logistics",
    avatar: "RK",
    lifecycleStage: "Customer",
    totalRevenue: 56000,
    dealsCount: 1,
    lastInteraction: "2026-04-19",
    tags: ["enterprise", "partner"],
  },
  {
    id: "c2",
    name: "Ethan Harper",
    email: "ethan@vertexsw.com",
    phone: "+1 (555) 489-6644",
    company: "Vertex Software",
    avatar: "EH",
    lifecycleStage: "Customer",
    totalRevenue: 61000,
    dealsCount: 2,
    lastInteraction: "2026-04-22",
    tags: ["SaaS", "growing"],
  },
  {
    id: "c3",
    name: "Sarah Mitchell",
    email: "sarah@technova.io",
    phone: "+1 (555) 201-4400",
    company: "TechNova Inc.",
    avatar: "SM",
    lifecycleStage: "Opportunity",
    totalRevenue: 0,
    dealsCount: 1,
    lastInteraction: "2026-04-18",
    tags: ["enterprise"],
  },
  {
    id: "c4",
    name: "James Thornton",
    email: "j.thornton@meridian.com",
    phone: "+1 (555) 309-7722",
    company: "Meridian Group",
    avatar: "JT",
    lifecycleStage: "Customer",
    totalRevenue: 78500,
    dealsCount: 1,
    lastInteraction: "2026-04-20",
    tags: ["finance", "mid-market"],
  },
  {
    id: "c5",
    name: "Nina Johansson",
    email: "nina@nordiccap.se",
    phone: "+46 70 123 4567",
    company: "Nordic Capital",
    avatar: "NJ",
    lifecycleStage: "Customer",
    totalRevenue: 120000,
    dealsCount: 1,
    lastInteraction: "2026-04-20",
    tags: ["finance", "enterprise", "europe"],
  },
  {
    id: "c6",
    name: "Elena Vasquez",
    email: "elena@clearstream.tv",
    phone: "+1 (555) 678-9900",
    company: "ClearStream Media",
    avatar: "EV",
    lifecycleStage: "SQL",
    totalRevenue: 0,
    dealsCount: 1,
    lastInteraction: "2026-04-21",
    tags: ["media"],
  },
  {
    id: "c7",
    name: "Benjamin Stark",
    email: "b.stark@harborins.com",
    phone: "+1 (555) 156-7890",
    company: "Harbor Insurance",
    avatar: "BS",
    lifecycleStage: "Opportunity",
    totalRevenue: 0,
    dealsCount: 1,
    lastInteraction: "2026-04-21",
    tags: ["insurance"],
  },
  {
    id: "c8",
    name: "Olivia Chang",
    email: "olivia@healthfirst.com",
    phone: "+1 (555) 378-5533",
    company: "HealthFirst Medical",
    avatar: "OC",
    lifecycleStage: "Opportunity",
    totalRevenue: 0,
    dealsCount: 1,
    lastInteraction: "2026-04-20",
    tags: ["healthcare"],
  },
  {
    id: "c9",
    name: "Daniel Carter",
    email: "daniel@pinpoint.co",
    phone: "+1 (555) 912-6655",
    company: "Pinpoint Marketing",
    avatar: "DC",
    lifecycleStage: "MQL",
    totalRevenue: 0,
    dealsCount: 0,
    lastInteraction: "2026-04-17",
    tags: ["marketing", "SMB"],
  },
  {
    id: "c10",
    name: "Noah Williams",
    email: "noah@greenenergy.io",
    phone: "+1 (555) 267-4422",
    company: "GreenEnergy Corp",
    avatar: "NW",
    lifecycleStage: "SQL",
    totalRevenue: 0,
    dealsCount: 1,
    lastInteraction: "2026-04-19",
    tags: ["energy"],
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm1",
    name: "Alex Rivera",
    email: "alex@salesforge.io",
    avatar: "AR",
    role: "Senior Account Executive",
    dealsClosedThisMonth: 4,
    totalRevenue: 196000,
    callsMade: 87,
    meetingsHeld: 23,
    conversionRate: 38,
    monthlyTarget: 200000,
    commission: 9800,
  },
  {
    id: "tm2",
    name: "Maria Chen",
    email: "maria@salesforge.io",
    avatar: "MC",
    role: "Enterprise Sales Manager",
    dealsClosedThisMonth: 3,
    totalRevenue: 276500,
    callsMade: 64,
    meetingsHeld: 31,
    conversionRate: 45,
    monthlyTarget: 250000,
    commission: 13825,
  },
  {
    id: "tm3",
    name: "David Park",
    email: "david@salesforge.io",
    avatar: "DP",
    role: "Account Executive",
    dealsClosedThisMonth: 2,
    totalRevenue: 71000,
    callsMade: 102,
    meetingsHeld: 18,
    conversionRate: 22,
    monthlyTarget: 120000,
    commission: 3550,
  },
  {
    id: "tm4",
    name: "Sophia Lee",
    email: "sophia@salesforge.io",
    avatar: "SL",
    role: "Business Development Rep",
    dealsClosedThisMonth: 1,
    totalRevenue: 31000,
    callsMade: 138,
    meetingsHeld: 14,
    conversionRate: 15,
    monthlyTarget: 80000,
    commission: 1550,
  },
  {
    id: "tm5",
    name: "Jordan Mills",
    email: "jordan@salesforge.io",
    avatar: "JM",
    role: "Account Executive",
    dealsClosedThisMonth: 3,
    totalRevenue: 89000,
    callsMade: 79,
    meetingsHeld: 21,
    conversionRate: 31,
    monthlyTarget: 120000,
    commission: 4450,
  },
  {
    id: "tm6",
    name: "Aisha Patel",
    email: "aisha@salesforge.io",
    avatar: "AP",
    role: "Senior Account Executive",
    dealsClosedThisMonth: 5,
    totalRevenue: 213000,
    callsMade: 71,
    meetingsHeld: 28,
    conversionRate: 42,
    monthlyTarget: 200000,
    commission: 10650,
  },
  {
    id: "tm7",
    name: "Carlos Mendez",
    email: "carlos@salesforge.io",
    avatar: "CM",
    role: "Sales Development Rep",
    dealsClosedThisMonth: 0,
    totalRevenue: 0,
    callsMade: 156,
    meetingsHeld: 8,
    conversionRate: 8,
    monthlyTarget: 50000,
    commission: 0,
  },
  {
    id: "tm8",
    name: "Rachel Thompson",
    email: "rachel@salesforge.io",
    avatar: "RT",
    role: "Account Manager",
    dealsClosedThisMonth: 2,
    totalRevenue: 52000,
    callsMade: 55,
    meetingsHeld: 17,
    conversionRate: 28,
    monthlyTarget: 100000,
    commission: 2600,
  },
];

export const mockTasks: Task[] = [
  {
    id: "tk1",
    title: "Follow up with TechNova on revised pricing",
    type: "Follow-up",
    status: "Pending",
    priority: "High",
    dueDate: "2026-04-25",
    assignedTo: "Alex Rivera",
    relatedTo: "TechNova Inc.",
    notes: "Pricing deck v3 attached",
  },
  {
    id: "tk2",
    title: "Demo call with Meridian Group",
    type: "Call",
    status: "Completed",
    priority: "Urgent",
    dueDate: "2026-04-20",
    assignedTo: "Maria Chen",
    relatedTo: "Meridian Group",
    notes: "Went well — legal review next",
  },
  {
    id: "tk3",
    title: "Send BrightPath proposal",
    type: "Proposal",
    status: "InProgress",
    priority: "Medium",
    dueDate: "2026-04-26",
    assignedTo: "David Park",
    relatedTo: "BrightPath Analytics",
    notes: "Waiting on final numbers",
  },
  {
    id: "tk4",
    title: "Contract review meeting — Nordic Capital",
    type: "Meeting",
    status: "Pending",
    priority: "Urgent",
    dueDate: "2026-04-23",
    assignedTo: "Maria Chen",
    relatedTo: "Nordic Capital",
    notes: "Legal team joining",
  },
  {
    id: "tk5",
    title: "Cold email sequence: Gulf Tech batch",
    type: "Email",
    status: "Pending",
    priority: "Medium",
    dueDate: "2026-04-27",
    assignedTo: "Sophia Lee",
    relatedTo: "Gulf Tech Solutions",
    notes: "Use template B",
  },
  {
    id: "tk6",
    title: "Quarterly review reminder — all AEs",
    type: "Reminder",
    status: "Pending",
    priority: "Low",
    dueDate: "2026-04-30",
    assignedTo: "Jordan Mills",
    relatedTo: "Internal",
    notes: "",
  },
  {
    id: "tk7",
    title: "ClearStream final negotiation call",
    type: "Call",
    status: "Pending",
    priority: "Urgent",
    dueDate: "2026-04-23",
    assignedTo: "Maria Chen",
    relatedTo: "ClearStream Media",
    notes: "Price concession limit approved",
  },
  {
    id: "tk8",
    title: "Onboarding call — Apex Logistics",
    type: "Meeting",
    status: "Completed",
    priority: "High",
    dueDate: "2026-04-22",
    assignedTo: "David Park",
    relatedTo: "Apex Logistics",
    notes: "Welcome kit sent",
  },
  {
    id: "tk9",
    title: "Email HealthFirst HIPAA checklist",
    type: "Email",
    status: "InProgress",
    priority: "High",
    dueDate: "2026-04-24",
    assignedTo: "Maria Chen",
    relatedTo: "HealthFirst Medical",
    notes: "Compliance doc attached",
  },
  {
    id: "tk10",
    title: "Pinpoint Marketing demo walkthrough",
    type: "Meeting",
    status: "Overdue",
    priority: "High",
    dueDate: "2026-04-21",
    assignedTo: "Alex Rivera",
    relatedTo: "Pinpoint Marketing",
    notes: "Reschedule needed",
  },
  {
    id: "tk11",
    title: "Harbor Insurance security docs",
    type: "Proposal",
    status: "Pending",
    priority: "Medium",
    dueDate: "2026-04-28",
    assignedTo: "David Park",
    relatedTo: "Harbor Insurance",
    notes: "Security team review",
  },
  {
    id: "tk12",
    title: "Follow up Summit Real Estate",
    type: "Follow-up",
    status: "Pending",
    priority: "Low",
    dueDate: "2026-04-30",
    assignedTo: "Alex Rivera",
    relatedTo: "Summit Real Estate",
    notes: "Post-conference",
  },
  {
    id: "tk13",
    title: "GreenEnergy ESG feature list",
    type: "Email",
    status: "Pending",
    priority: "Medium",
    dueDate: "2026-04-26",
    assignedTo: "Alex Rivera",
    relatedTo: "GreenEnergy Corp",
    notes: "Request from Noah",
  },
  {
    id: "tk14",
    title: "Paris Consulting RFP follow-up",
    type: "Follow-up",
    status: "Pending",
    priority: "Medium",
    dueDate: "2026-04-29",
    assignedTo: "Sophia Lee",
    relatedTo: "Paris Consulting",
    notes: "2-week evaluation window",
  },
  {
    id: "tk15",
    title: "Team pipeline review meeting",
    type: "Meeting",
    status: "Pending",
    priority: "High",
    dueDate: "2026-04-25",
    assignedTo: "Jordan Mills",
    relatedTo: "Internal",
    notes: "Weekly sync",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "lead",
    title: "New lead assigned",
    message: "Fatima Al-Rashid from Gulf Tech has been assigned to you",
    timestamp: "2026-04-22T09:15:00",
    read: false,
    avatar: "FA",
  },
  {
    id: "n2",
    type: "deal",
    title: "Deal stage updated",
    message: "Nordic Capital moved to Contract stage",
    timestamp: "2026-04-22T08:45:00",
    read: false,
    avatar: "NC",
  },
  {
    id: "n3",
    type: "reminder",
    title: "Follow-up due today",
    message: "TechNova Inc. follow-up is due in 2 hours",
    timestamp: "2026-04-22T08:00:00",
    read: false,
  },
  {
    id: "n4",
    type: "team",
    title: "Aisha closed a deal",
    message: "Aisha Patel closed Vertex Software — $61,000",
    timestamp: "2026-04-21T17:30:00",
    read: false,
    avatar: "AP",
  },
  {
    id: "n5",
    type: "deal",
    title: "Proposal accepted",
    message: "Meridian Group accepted the revised proposal",
    timestamp: "2026-04-21T14:00:00",
    read: true,
    avatar: "MG",
  },
  {
    id: "n6",
    type: "system",
    title: "Monthly report ready",
    message: "Your April performance report is available",
    timestamp: "2026-04-21T09:00:00",
    read: true,
  },
  {
    id: "n7",
    type: "reminder",
    title: "Meeting in 30 minutes",
    message: "Contract review with Nordic Capital starts at 3:00 PM",
    timestamp: "2026-04-21T14:30:00",
    read: true,
  },
  {
    id: "n8",
    type: "lead",
    title: "Lead status changed",
    message: "Nina Johansson progressed to Negotiation stage",
    timestamp: "2026-04-20T16:00:00",
    read: true,
    avatar: "NJ",
  },
  {
    id: "n9",
    type: "team",
    title: "New team message",
    message: "Maria Chen mentioned you in Pipeline Review",
    timestamp: "2026-04-20T11:00:00",
    read: true,
    avatar: "MC",
  },
  {
    id: "n10",
    type: "system",
    title: "Integration sync complete",
    message: "Salesforce sync completed — 24 records updated",
    timestamp: "2026-04-20T06:00:00",
    read: true,
  },
  {
    id: "n11",
    type: "deal",
    title: "Deal at risk",
    message: "FutureLabs Corp deal hasn't been updated in 14 days",
    timestamp: "2026-04-19T10:00:00",
    read: true,
  },
  {
    id: "n12",
    type: "lead",
    title: "High-value lead added",
    message: "Elena Vasquez — ClearStream Media added as Urgent priority",
    timestamp: "2026-04-18T15:30:00",
    read: true,
    avatar: "EV",
  },
];

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "ce1",
    title: "Nordic Capital Contract Review",
    type: "Meeting",
    start: "2026-04-23T15:00:00",
    end: "2026-04-23T16:00:00",
    attendees: ["Maria Chen", "Nina Johansson", "Legal Team"],
    description: "Final contract review and signing",
    recurring: false,
    dealId: "d4",
  },
  {
    id: "ce2",
    title: "ClearStream Final Negotiation",
    type: "Call",
    start: "2026-04-23T10:00:00",
    end: "2026-04-23T11:00:00",
    attendees: ["Maria Chen", "Elena Vasquez"],
    description: "Final pricing negotiation call",
    recurring: false,
    dealId: "d6",
  },
  {
    id: "ce3",
    title: "Weekly Pipeline Review",
    type: "Meeting",
    start: "2026-04-25T09:00:00",
    end: "2026-04-25T10:00:00",
    attendees: ["Alex Rivera", "Maria Chen", "David Park", "Sophia Lee"],
    description: "Weekly team pipeline sync",
    recurring: true,
  },
  {
    id: "ce4",
    title: "TechNova Follow-up Call",
    type: "Call",
    start: "2026-04-25T14:00:00",
    end: "2026-04-25T14:30:00",
    attendees: ["Alex Rivera", "Sarah Mitchell"],
    description: "Pricing discussion follow-up",
    recurring: false,
    dealId: "d1",
  },
  {
    id: "ce5",
    title: "Harbor Insurance Demo",
    type: "Meeting",
    start: "2026-04-28T11:00:00",
    end: "2026-04-28T12:00:00",
    attendees: ["David Park", "Benjamin Stark"],
    description: "Security features demonstration",
    recurring: false,
    dealId: "d8",
  },
  {
    id: "ce6",
    title: "Apex Logistics Onboarding",
    type: "Meeting",
    start: "2026-04-29T10:00:00",
    end: "2026-04-29T11:30:00",
    attendees: ["David Park", "Robert Kim"],
    description: "Customer onboarding kickoff",
    recurring: false,
    customerId: "c1",
  },
  {
    id: "ce7",
    title: "Monthly Sales Review",
    type: "Meeting",
    start: "2026-04-30T14:00:00",
    end: "2026-04-30T16:00:00",
    attendees: ["All Sales Team"],
    description: "April monthly review and May targets",
    recurring: true,
  },
  {
    id: "ce8",
    title: "HealthFirst Compliance Discussion",
    type: "Call",
    start: "2026-04-24T15:00:00",
    end: "2026-04-24T16:00:00",
    attendees: ["Maria Chen", "Olivia Chang"],
    description: "HIPAA compliance requirements",
    recurring: false,
    dealId: "d9",
  },
  {
    id: "ce9",
    title: "Sales Strategy Workshop",
    type: "Meeting",
    start: "2026-04-26T09:00:00",
    end: "2026-04-26T12:00:00",
    attendees: ["Entire Sales Team"],
    description: "Q2 strategy planning session",
    recurring: false,
  },
  {
    id: "ce10",
    title: "GreenEnergy Product Walkthrough",
    type: "Meeting",
    start: "2026-04-26T14:00:00",
    end: "2026-04-26T15:00:00",
    attendees: ["Alex Rivera", "Noah Williams"],
    description: "ESG features demo",
    recurring: false,
    dealId: "d11",
  },
];

export const mockMessages: Message[] = [
  {
    id: "m1",
    channel: "Email",
    from: "sarah@technova.io",
    to: "alex@salesforge.io",
    subject: "Re: Revised Pricing Proposal",
    body: "Hi Alex, thanks for the updated pricing. I've reviewed it with our CFO and we have a few questions before we proceed...",
    timestamp: "2026-04-22T10:30:00",
    status: "received",
    attachments: [],
  },
  {
    id: "m2",
    channel: "Call",
    from: "alex@salesforge.io",
    to: "j.thornton@meridian.com",
    subject: "Demo Call Recording",
    body: "45-minute demo call completed. James was very engaged. Legal team needs to review contract next.",
    timestamp: "2026-04-20T15:00:00",
    status: "completed",
    attachments: [],
  },
  {
    id: "m3",
    channel: "Email",
    from: "alex@salesforge.io",
    to: "sarah@technova.io",
    subject: "Revised Pricing Proposal — TechNova Enterprise",
    body: "Hi Sarah, as discussed, please find the revised pricing proposal attached. Key highlights: Annual commitment discount of 15%...",
    timestamp: "2026-04-19T14:00:00",
    status: "sent",
    attachments: ["proposal-v3.pdf"],
  },
  {
    id: "m4",
    channel: "WhatsApp",
    from: "nina@nordiccap.se",
    to: "maria@salesforge.io",
    subject: "Contract update",
    body: "Maria, our lawyers finished the review. We're good to sign on Thursday!",
    timestamp: "2026-04-22T09:00:00",
    status: "received",
    attachments: [],
  },
  {
    id: "m5",
    channel: "SMS",
    from: "maria@salesforge.io",
    to: "nina@nordiccap.se",
    subject: "",
    body: "Great news Nina! I'll send the calendar invite for Thursday at 3pm CET.",
    timestamp: "2026-04-22T09:05:00",
    status: "sent",
    attachments: [],
  },
  {
    id: "m6",
    channel: "Email",
    from: "elena@clearstream.tv",
    to: "maria@salesforge.io",
    subject: "Negotiation Update",
    body: "Maria, we've spoken with our board. We can agree to the enterprise tier but need the volume discount extended to 2 years.",
    timestamp: "2026-04-21T16:00:00",
    status: "received",
    attachments: [],
  },
  {
    id: "m7",
    channel: "Note",
    from: "david@salesforge.io",
    to: "internal",
    subject: "Apex Logistics — Post-Sale Notes",
    body: "Onboarding went smoothly. Robert Kim is an excellent contact. Expansion opportunity in Q3 for additional licenses.",
    timestamp: "2026-04-22T11:00:00",
    status: "internal",
    attachments: [],
  },
  {
    id: "m8",
    channel: "Email",
    from: "b.stark@harborins.com",
    to: "david@salesforge.io",
    subject: "Security Assessment Requirements",
    body: "David, we'll need your SOC 2 Type II documentation and the security assessment results before we can proceed.",
    timestamp: "2026-04-21T13:00:00",
    status: "received",
    attachments: ["security-requirements.pdf"],
  },
];

// Helper functions
export function getLeadsByStage(leads: Lead[]) {
  const stages = [
    "New",
    "Contacted",
    "Qualified",
    "Proposal",
    "Negotiation",
    "Won",
    "Lost",
  ] as const;
  return stages.reduce(
    (acc, stage) => {
      acc[stage] = leads.filter((l) => l.status === stage);
      return acc;
    },
    {} as Record<string, Lead[]>,
  );
}

export function getDealsByStage(deals: Deal[]) {
  const stages = [
    "Prospect",
    "Qualified",
    "Proposal",
    "Negotiation",
    "Contract",
    "Won",
    "Lost",
  ] as const;
  return stages.reduce(
    (acc, stage) => {
      acc[stage] = deals.filter((d) => d.stage === stage);
      return acc;
    },
    {} as Record<string, Deal[]>,
  );
}

export function getTeamMetrics(members: TeamMember[]) {
  return {
    totalRevenue: members.reduce((sum, m) => sum + m.totalRevenue, 0),
    totalDeals: members.reduce((sum, m) => sum + m.dealsClosedThisMonth, 0),
    totalCalls: members.reduce((sum, m) => sum + m.callsMade, 0),
    avgConversionRate:
      members.reduce((sum, m) => sum + m.conversionRate, 0) / members.length,
  };
}

export function getActivityFeed(): ActivityFeedItem[] {
  return [
    {
      id: "af1",
      type: "deal_won",
      description: "Closed deal with Vertex Software",
      user: "Alex Rivera",
      timestamp: "2026-04-22T10:00:00",
      relatedTo: "Vertex Software",
    },
    {
      id: "af2",
      type: "lead_created",
      description: "New lead: Fatima Al-Rashid added",
      user: "Sophia Lee",
      timestamp: "2026-04-22T09:30:00",
      relatedTo: "Gulf Tech Solutions",
    },
    {
      id: "af3",
      type: "call_completed",
      description: "Completed discovery call",
      user: "Maria Chen",
      timestamp: "2026-04-22T08:45:00",
      relatedTo: "ClearStream Media",
    },
    {
      id: "af4",
      type: "meeting_scheduled",
      description: "Contract review scheduled",
      user: "Maria Chen",
      timestamp: "2026-04-21T17:00:00",
      relatedTo: "Nordic Capital",
    },
    {
      id: "af5",
      type: "deal_moved",
      description: "Meridian Group moved to Contract",
      user: "Maria Chen",
      timestamp: "2026-04-21T14:00:00",
      relatedTo: "Meridian Group",
    },
    {
      id: "af6",
      type: "email_sent",
      description: "Sent revised proposal",
      user: "Alex Rivera",
      timestamp: "2026-04-20T14:00:00",
      relatedTo: "TechNova Inc.",
    },
    {
      id: "af7",
      type: "lead_created",
      description: "New enterprise lead from LinkedIn",
      user: "David Park",
      timestamp: "2026-04-20T11:00:00",
      relatedTo: "BrightPath Analytics",
    },
    {
      id: "af8",
      type: "deal_won",
      description: "Apex Logistics deal closed — $56K",
      user: "David Park",
      timestamp: "2026-04-19T16:00:00",
      relatedTo: "Apex Logistics",
    },
  ];
}

export const revenueChartData = [
  { month: "Nov", revenue: 185000, target: 200000 },
  { month: "Dec", revenue: 241000, target: 220000 },
  { month: "Jan", revenue: 198000, target: 210000 },
  { month: "Feb", revenue: 267000, target: 240000 },
  { month: "Mar", revenue: 312000, target: 280000 },
  { month: "Apr", revenue: 289000, target: 300000 },
];

export const conversionChartData = [
  { stage: "Leads", count: 320, fill: "var(--color-chart-2)" },
  { stage: "Qualified", count: 204, fill: "var(--color-chart-1)" },
  { stage: "Proposal", count: 118, fill: "var(--color-chart-3)" },
  { stage: "Negotiation", count: 67, fill: "var(--color-chart-4)" },
  { stage: "Won", count: 38, fill: "var(--color-chart-5)" },
];

export const teamPerformanceData = [
  { name: "Alex", revenue: 196, target: 200 },
  { name: "Maria", revenue: 276, target: 250 },
  { name: "David", revenue: 71, target: 120 },
  { name: "Sophia", revenue: 31, target: 80 },
  { name: "Jordan", revenue: 89, target: 120 },
  { name: "Aisha", revenue: 213, target: 200 },
];
